START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'bousSOle') THEN
CREATE SCHEMA "bousSOle";
END IF;
END $EF$;

CREATE TABLE IF NOT EXISTS "bousSOle"."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );

CREATE TABLE "bousSOle"."ElementNorms" (
                                           "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                           "NormCollection" text NOT NULL,
                                           "NormCode" text NOT NULL,
                                           "NormName" text NOT NULL,
                                           "MeasurementUnit" text NOT NULL,
                                           "BaseNorm" real NOT NULL,
                                           "NormTypeByDistance" text NOT NULL,
                                           "DistanceNorm" real NULL,
                                           CONSTRAINT "PK_ElementNorms" PRIMARY KEY ("Id")
);

CREATE TABLE "bousSOle"."Okrug" (
                                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                    "Name" text NOT NULL,
                                    CONSTRAINT "PK_Okrug" PRIMARY KEY ("Id")
);

CREATE TABLE "bousSOle"."Persons" (
                                      "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                      "PersonInn" text NOT NULL,
                                      "Surname" text NOT NULL,
                                      "Name" text NOT NULL,
                                      "Patronymic" text NOT NULL,
                                      "PhoneNumber" text NOT NULL,
                                      "EMail" text NOT NULL,
                                      CONSTRAINT "PK_Persons" PRIMARY KEY ("Id")
);

CREATE TABLE "bousSOle"."WorkProject" (
                                          "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                          "Name" text NOT NULL,
                                          "ActivityField" text NOT NULL,
                                          "Region" text NOT NULL,
                                          CONSTRAINT "PK_WorkProject" PRIMARY KEY ("Id")
);

CREATE TABLE "bousSOle"."Region" (
                                     "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                     "Name" text NOT NULL,
                                     "OkrugId" integer NOT NULL,
                                     CONSTRAINT "PK_Region" PRIMARY KEY ("Id"),
                                     CONSTRAINT "FK_Region_Okrug_OkrugId" FOREIGN KEY ("OkrugId") REFERENCES "bousSOle"."Okrug" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."Passport" (
                                       "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                       "PersonId" integer NOT NULL,
                                       "BirthDate" timestamp with time zone NOT NULL,
                                       "BirthPlace" text NOT NULL,
                                       "Series" text NOT NULL,
                                       "Number" text NOT NULL,
                                       "IssueDate" timestamp with time zone NOT NULL,
                                       "IssuedBy" text NOT NULL,
                                       "DivisionCode" text NOT NULL,
                                       "RegistrationAddress" text NOT NULL,
                                       "RegistrationIndex" text NOT NULL,
                                       "SNILS" text NOT NULL,
                                       "OMS" text NOT NULL,
                                       CONSTRAINT "PK_Passport" PRIMARY KEY ("Id"),
                                       CONSTRAINT "FK_Passport_Persons_PersonId" FOREIGN KEY ("PersonId") REFERENCES "bousSOle"."Persons" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."PersonMerch" (
                                          "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                          "PersonId" integer NOT NULL,
                                          "ClothesSize" integer NOT NULL,
                                          "PersonHeight" integer NOT NULL,
                                          "ShoeSize" integer NOT NULL,
                                          CONSTRAINT "PK_PersonMerch" PRIMARY KEY ("Id"),
                                          CONSTRAINT "FK_PersonMerch_Persons_PersonId" FOREIGN KEY ("PersonId") REFERENCES "bousSOle"."Persons" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."ProfessionalEducation" (
                                                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                    "PersonId" integer NOT NULL,
                                                    "Profession" text NOT NULL,
                                                    "Category" text NULL,
                                                    "CertificateNumber" text NOT NULL,
                                                    CONSTRAINT "PK_ProfessionalEducation" PRIMARY KEY ("Id"),
                                                    CONSTRAINT "FK_ProfessionalEducation_Persons_PersonId" FOREIGN KEY ("PersonId") REFERENCES "bousSOle"."Persons" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."Users" (
                                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                    "PersonId" integer NOT NULL,
                                    "Password" text NOT NULL,
                                    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
                                    CONSTRAINT "FK_Users_Persons_PersonId" FOREIGN KEY ("PersonId") REFERENCES "bousSOle"."Persons" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."WorkProjectImplementation" (
                                                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                        "WorkProjectId" integer NOT NULL,
                                                        "Year" integer NOT NULL,
                                                        "Season" text NOT NULL,
                                                        CONSTRAINT "PK_WorkProjectImplementation" PRIMARY KEY ("Id"),
                                                        CONSTRAINT "FK_WorkProjectImplementation_WorkProject_WorkProjectId" FOREIGN KEY ("WorkProjectId") REFERENCES "bousSOle"."WorkProject" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."Shtab" (
                                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                    "Name" text NOT NULL,
                                    "ShtabRank" text NOT NULL,
                                    "ParentShtabId" integer NULL,
                                    "RegionId" integer NOT NULL,
                                    CONSTRAINT "PK_Shtab" PRIMARY KEY ("Id"),
                                    CONSTRAINT "FK_Shtab_Region_RegionId" FOREIGN KEY ("RegionId") REFERENCES "bousSOle"."Region" ("Id") ON DELETE CASCADE,
                                    CONSTRAINT "FK_Shtab_Shtab_ParentShtabId" FOREIGN KEY ("ParentShtabId") REFERENCES "bousSOle"."Shtab" ("Id")
);

CREATE TABLE "bousSOle"."ActivityCoefficient" (
                                                  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                  "WorkProjectImplementationId" integer NOT NULL,
                                                  "SquadActivityStatus" text NOT NULL,
                                                  "RatingPoints" real NOT NULL,
                                                  CONSTRAINT "PK_ActivityCoefficient" PRIMARY KEY ("Id"),
                                                  CONSTRAINT "FK_ActivityCoefficient_WorkProjectImplementation_WorkProjectIm~" FOREIGN KEY ("WorkProjectImplementationId") REFERENCES "bousSOle"."WorkProjectImplementation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."AdditionalCoefficient" (
                                                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                    "WorkProjectImplementationId" integer NOT NULL,
                                                    "Name" text NOT NULL,
                                                    "Transcript" text NOT NULL,
                                                    "MaxPoints" real NOT NULL,
                                                    CONSTRAINT "PK_AdditionalCoefficient" PRIMARY KEY ("Id"),
                                                    CONSTRAINT "FK_AdditionalCoefficient_WorkProjectImplementation_WorkProject~" FOREIGN KEY ("WorkProjectImplementationId") REFERENCES "bousSOle"."WorkProjectImplementation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."DisciplineCoefficient" (
                                                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                    "WorkProjectImplementationId" integer NOT NULL,
                                                    "ViolationType" text NOT NULL,
                                                    "PointsReduction" real NOT NULL,
                                                    CONSTRAINT "PK_DisciplineCoefficient" PRIMARY KEY ("Id"),
                                                    CONSTRAINT "FK_DisciplineCoefficient_WorkProjectImplementation_WorkProject~" FOREIGN KEY ("WorkProjectImplementationId") REFERENCES "bousSOle"."WorkProjectImplementation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."ProductivityCoefficient" (
                                                      "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                      "WorkProjectImplementationId" integer NOT NULL,
                                                      "ProizvodkaStartDate" timestamp with time zone NOT NULL,
                                                      "RatingPoints" integer NOT NULL,
                                                      CONSTRAINT "PK_ProductivityCoefficient" PRIMARY KEY ("Id"),
                                                      CONSTRAINT "FK_ProductivityCoefficient_WorkProjectImplementation_WorkProje~" FOREIGN KEY ("WorkProjectImplementationId") REFERENCES "bousSOle"."WorkProjectImplementation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."ProjectEvent" (
                                           "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                           "WorkProjectImplementationId" integer NOT NULL,
                                           "ProjectEventType" text NOT NULL,
                                           "Name" text NOT NULL,
                                           "Date" timestamp with time zone NOT NULL,
                                           CONSTRAINT "PK_ProjectEvent" PRIMARY KEY ("Id"),
                                           CONSTRAINT "FK_ProjectEvent_WorkProjectImplementation_WorkProjectImplement~" FOREIGN KEY ("WorkProjectImplementationId") REFERENCES "bousSOle"."WorkProjectImplementation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."Institutions" (
                                           "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                           "FullName" text NOT NULL,
                                           "ShortName" text NOT NULL,
                                           "ShtabId" integer NOT NULL,
                                           "AdministratorTitle" text NOT NULL,
                                           "AdministratorSurname" text NOT NULL,
                                           "AdministratorName" text NOT NULL,
                                           "AdministratorPatronymic" text NOT NULL,
                                           "StructWebsite" text NOT NULL,
                                           CONSTRAINT "PK_Institutions" PRIMARY KEY ("Id"),
                                           CONSTRAINT "FK_Institutions_Shtab_ShtabId" FOREIGN KEY ("ShtabId") REFERENCES "bousSOle"."Shtab" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."ShtabMember" (
                                          "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                          "PersonId" integer NOT NULL,
                                          "ShtabId" integer NOT NULL,
                                          "ShtabMemberRank" text NOT NULL,
                                          "Specialty" text NULL,
                                          "IsActive" boolean NOT NULL,
                                          CONSTRAINT "PK_ShtabMember" PRIMARY KEY ("Id"),
                                          CONSTRAINT "FK_ShtabMember_Persons_PersonId" FOREIGN KEY ("PersonId") REFERENCES "bousSOle"."Persons" ("Id") ON DELETE CASCADE,
                                          CONSTRAINT "FK_ShtabMember_Shtab_ShtabId" FOREIGN KEY ("ShtabId") REFERENCES "bousSOle"."Shtab" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."Squads" (
                                     "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                     "Name" text NOT NULL,
                                     "ShtabId" integer NOT NULL,
                                     "ActivityField" text NOT NULL,
                                     "VkUrl" text NULL,
                                     CONSTRAINT "PK_Squads" PRIMARY KEY ("Id"),
                                     CONSTRAINT "FK_Squads_Shtab_ShtabId" FOREIGN KEY ("ShtabId") REFERENCES "bousSOle"."Shtab" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."Education" (
                                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                        "PersonId" integer NOT NULL,
                                        "InstitutionId" integer NOT NULL,
                                        "Faculty" text NOT NULL,
                                        "Specialization" text NOT NULL,
                                        "Course" text NOT NULL,
                                        "ExpectedGraduationYear" integer NOT NULL,
                                        CONSTRAINT "PK_Education" PRIMARY KEY ("Id"),
                                        CONSTRAINT "FK_Education_Institutions_InstitutionId" FOREIGN KEY ("InstitutionId") REFERENCES "bousSOle"."Institutions" ("Id") ON DELETE CASCADE,
                                        CONSTRAINT "FK_Education_Persons_PersonId" FOREIGN KEY ("PersonId") REFERENCES "bousSOle"."Persons" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."FactWorks" (
                                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                        "Date" timestamp with time zone NOT NULL,
                                        "SquadId" integer NOT NULL,
                                        "WorkName" text NOT NULL,
                                        "ElementNormId" integer NOT NULL,
                                        "Quantity" real NOT NULL,
                                        "Distance" integer NULL,
                                        CONSTRAINT "PK_FactWorks" PRIMARY KEY ("Id"),
                                        CONSTRAINT "FK_FactWorks_ElementNorms_ElementNormId" FOREIGN KEY ("ElementNormId") REFERENCES "bousSOle"."ElementNorms" ("Id") ON DELETE CASCADE,
                                        CONSTRAINT "FK_FactWorks_Squads_SquadId" FOREIGN KEY ("SquadId") REFERENCES "bousSOle"."Squads" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."SquadMembers" (
                                           "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                           "PersonId" integer NOT NULL,
                                           "MemberRank" text NOT NULL,
                                           "YearEnlisted" integer NOT NULL,
                                           "IsActive" boolean NOT NULL,
                                           "SquadId" integer NOT NULL,
                                           CONSTRAINT "PK_SquadMembers" PRIMARY KEY ("Id"),
                                           CONSTRAINT "FK_SquadMembers_Persons_PersonId" FOREIGN KEY ("PersonId") REFERENCES "bousSOle"."Persons" ("Id") ON DELETE CASCADE,
                                           CONSTRAINT "FK_SquadMembers_Squads_SquadId" FOREIGN KEY ("SquadId") REFERENCES "bousSOle"."Squads" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."SquadProjectParticipation" (
                                                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                        "WorkProjectImplementationId" integer NOT NULL,
                                                        "SquadId" integer NOT NULL,
                                                        "SquadApplicationStatus" text NOT NULL,
                                                        CONSTRAINT "PK_SquadProjectParticipation" PRIMARY KEY ("Id"),
                                                        CONSTRAINT "FK_SquadProjectParticipation_Squads_SquadId" FOREIGN KEY ("SquadId") REFERENCES "bousSOle"."Squads" ("Id") ON DELETE CASCADE,
                                                        CONSTRAINT "FK_SquadProjectParticipation_WorkProjectImplementation_WorkPro~" FOREIGN KEY ("WorkProjectImplementationId") REFERENCES "bousSOle"."WorkProjectImplementation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."CalculatedFactWork" (
                                                 "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                 "FactWorkId" integer NOT NULL,
                                                 "Quantity" real NOT NULL,
                                                 "ElementNormId" integer NULL,
                                                 "Distance" integer NULL,
                                                 CONSTRAINT "PK_CalculatedFactWork" PRIMARY KEY ("Id"),
                                                 CONSTRAINT "FK_CalculatedFactWork_ElementNorms_ElementNormId" FOREIGN KEY ("ElementNormId") REFERENCES "bousSOle"."ElementNorms" ("Id"),
                                                 CONSTRAINT "FK_CalculatedFactWork_FactWorks_FactWorkId" FOREIGN KEY ("FactWorkId") REFERENCES "bousSOle"."FactWorks" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."PlanWorks" (
                                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                        "Date" timestamp with time zone NOT NULL,
                                        "SquadMemberId" integer NOT NULL,
                                        "WorkerActivityStatus" integer NOT NULL,
                                        "WorkHours" real NOT NULL,
                                        CONSTRAINT "PK_PlanWorks" PRIMARY KEY ("Id"),
                                        CONSTRAINT "FK_PlanWorks_SquadMembers_SquadMemberId" FOREIGN KEY ("SquadMemberId") REFERENCES "bousSOle"."SquadMembers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."SquadMemberWorkingDay" (
                                                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                    "SquadMemberId" integer NOT NULL,
                                                    "Date" timestamp with time zone NOT NULL,
                                                    "WorkerActivityStatus" text NOT NULL,
                                                    "WorkingHours" real NOT NULL,
                                                    CONSTRAINT "PK_SquadMemberWorkingDay" PRIMARY KEY ("Id"),
                                                    CONSTRAINT "FK_SquadMemberWorkingDay_SquadMembers_SquadMemberId" FOREIGN KEY ("SquadMemberId") REFERENCES "bousSOle"."SquadMembers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."SquadMemberWorkTimeSchedule" (
                                                          "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                          "SquadMemberId" integer NOT NULL,
                                                          "WorkDays" real NOT NULL,
                                                          "ChillDays" real NOT NULL,
                                                          "WorkStartDay" timestamp with time zone NOT NULL,
                                                          CONSTRAINT "PK_SquadMemberWorkTimeSchedule" PRIMARY KEY ("Id"),
                                                          CONSTRAINT "FK_SquadMemberWorkTimeSchedule_SquadMembers_SquadMemberId" FOREIGN KEY ("SquadMemberId") REFERENCES "bousSOle"."SquadMembers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."SquadAdditionalCoefficientParticipation" (
                                                                      "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                                      "SquadProjectParticipationId" integer NOT NULL,
                                                                      "AdditionalCoefficientId" integer NOT NULL,
                                                                      "RatingPoints" real NOT NULL,
                                                                      CONSTRAINT "PK_SquadAdditionalCoefficientParticipation" PRIMARY KEY ("Id"),
                                                                      CONSTRAINT "FK_SquadAdditionalCoefficientParticipation_AdditionalCoefficie~" FOREIGN KEY ("AdditionalCoefficientId") REFERENCES "bousSOle"."AdditionalCoefficient" ("Id") ON DELETE CASCADE,
                                                                      CONSTRAINT "FK_SquadAdditionalCoefficientParticipation_SquadProjectPartici~" FOREIGN KEY ("SquadProjectParticipationId") REFERENCES "bousSOle"."SquadProjectParticipation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "bousSOle"."SquadEventParticipation" (
                                                      "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                      "SquadProjectParticipationId" integer NOT NULL,
                                                      "ProjectEventId" integer NOT NULL,
                                                      "ActivityCoefficientId" integer NULL,
                                                      CONSTRAINT "PK_SquadEventParticipation" PRIMARY KEY ("Id"),
                                                      CONSTRAINT "FK_SquadEventParticipation_ActivityCoefficient_ActivityCoeffic~" FOREIGN KEY ("ActivityCoefficientId") REFERENCES "bousSOle"."ActivityCoefficient" ("Id"),
                                                      CONSTRAINT "FK_SquadEventParticipation_ProjectEvent_ProjectEventId" FOREIGN KEY ("ProjectEventId") REFERENCES "bousSOle"."ProjectEvent" ("Id") ON DELETE CASCADE,
                                                      CONSTRAINT "FK_SquadEventParticipation_SquadProjectParticipation_SquadProj~" FOREIGN KEY ("SquadProjectParticipationId") REFERENCES "bousSOle"."SquadProjectParticipation" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ActivityCoefficient_WorkProjectImplementationId" ON "bousSOle"."ActivityCoefficient" ("WorkProjectImplementationId");

CREATE INDEX "IX_AdditionalCoefficient_WorkProjectImplementationId" ON "bousSOle"."AdditionalCoefficient" ("WorkProjectImplementationId");

CREATE INDEX "IX_CalculatedFactWork_ElementNormId" ON "bousSOle"."CalculatedFactWork" ("ElementNormId");

CREATE INDEX "IX_CalculatedFactWork_FactWorkId" ON "bousSOle"."CalculatedFactWork" ("FactWorkId");

CREATE INDEX "IX_DisciplineCoefficient_WorkProjectImplementationId" ON "bousSOle"."DisciplineCoefficient" ("WorkProjectImplementationId");

CREATE INDEX "IX_Education_InstitutionId" ON "bousSOle"."Education" ("InstitutionId");

CREATE INDEX "IX_Education_PersonId" ON "bousSOle"."Education" ("PersonId");

CREATE INDEX "IX_FactWorks_ElementNormId" ON "bousSOle"."FactWorks" ("ElementNormId");

CREATE INDEX "IX_FactWorks_SquadId" ON "bousSOle"."FactWorks" ("SquadId");

CREATE INDEX "IX_Institutions_ShtabId" ON "bousSOle"."Institutions" ("ShtabId");

CREATE INDEX "IX_Passport_PersonId" ON "bousSOle"."Passport" ("PersonId");

CREATE INDEX "IX_PersonMerch_PersonId" ON "bousSOle"."PersonMerch" ("PersonId");

CREATE INDEX "IX_PlanWorks_SquadMemberId" ON "bousSOle"."PlanWorks" ("SquadMemberId");

CREATE INDEX "IX_ProductivityCoefficient_WorkProjectImplementationId" ON "bousSOle"."ProductivityCoefficient" ("WorkProjectImplementationId");

CREATE INDEX "IX_ProfessionalEducation_PersonId" ON "bousSOle"."ProfessionalEducation" ("PersonId");

CREATE INDEX "IX_ProjectEvent_WorkProjectImplementationId" ON "bousSOle"."ProjectEvent" ("WorkProjectImplementationId");

CREATE INDEX "IX_Region_OkrugId" ON "bousSOle"."Region" ("OkrugId");

CREATE INDEX "IX_Shtab_ParentShtabId" ON "bousSOle"."Shtab" ("ParentShtabId");

CREATE INDEX "IX_Shtab_RegionId" ON "bousSOle"."Shtab" ("RegionId");

CREATE INDEX "IX_ShtabMember_PersonId" ON "bousSOle"."ShtabMember" ("PersonId");

CREATE INDEX "IX_ShtabMember_ShtabId" ON "bousSOle"."ShtabMember" ("ShtabId");

CREATE INDEX "IX_SquadAdditionalCoefficientParticipation_AdditionalCoefficie~" ON "bousSOle"."SquadAdditionalCoefficientParticipation" ("AdditionalCoefficientId");

CREATE INDEX "IX_SquadAdditionalCoefficientParticipation_SquadProjectPartici~" ON "bousSOle"."SquadAdditionalCoefficientParticipation" ("SquadProjectParticipationId");

CREATE INDEX "IX_SquadEventParticipation_ActivityCoefficientId" ON "bousSOle"."SquadEventParticipation" ("ActivityCoefficientId");

CREATE INDEX "IX_SquadEventParticipation_ProjectEventId" ON "bousSOle"."SquadEventParticipation" ("ProjectEventId");

CREATE INDEX "IX_SquadEventParticipation_SquadProjectParticipationId" ON "bousSOle"."SquadEventParticipation" ("SquadProjectParticipationId");

CREATE INDEX "IX_SquadMembers_PersonId" ON "bousSOle"."SquadMembers" ("PersonId");

CREATE INDEX "IX_SquadMembers_SquadId" ON "bousSOle"."SquadMembers" ("SquadId");

CREATE INDEX "IX_SquadMemberWorkingDay_SquadMemberId" ON "bousSOle"."SquadMemberWorkingDay" ("SquadMemberId");

CREATE INDEX "IX_SquadMemberWorkTimeSchedule_SquadMemberId" ON "bousSOle"."SquadMemberWorkTimeSchedule" ("SquadMemberId");

CREATE INDEX "IX_SquadProjectParticipation_SquadId" ON "bousSOle"."SquadProjectParticipation" ("SquadId");

CREATE INDEX "IX_SquadProjectParticipation_WorkProjectImplementationId" ON "bousSOle"."SquadProjectParticipation" ("WorkProjectImplementationId");

CREATE INDEX "IX_Squads_ShtabId" ON "bousSOle"."Squads" ("ShtabId");

CREATE INDEX "IX_Users_PersonId" ON "bousSOle"."Users" ("PersonId");

CREATE INDEX "IX_WorkProjectImplementation_WorkProjectId" ON "bousSOle"."WorkProjectImplementation" ("WorkProjectId");

INSERT INTO "bousSOle"."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230629144159_Initial', '7.0.0');

COMMIT;
