version: "3"
services:
  postgres:
    image: medveden91.ddns.net/boussole/dependency_proxy/containers/postgres:13
    restart: always
    ports:
      - "5234:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: Den
      POSTGRES_PASSWORD: $POSTGRESPASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
    external: true